---
- name: Setup Kubernetes Control Plane
  hosts: localhost
  become: yes
  vars:
  tasks:
    - name: Initialize Kubernetes Master
      ansible.builtin.import_tasks: tasks/control_plane_init.yaml
    - name: Setup kubeconfig for master access
      ansible.builtin.include_tasks: tasks/setup_kubectl.yaml

- name: Install Pod Network Add-on (e.g., Flannel)
  hosts: localhost
  tasks:
    - name: Install Pod Network Add-on
      ansible.builtin.include_tasks: tasks/pod_network.yaml