---
- name: Apply Flannel network configuration
  ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  register: flannel_install
  changed_when: flannel_install.rc == 0

- name: Wait for Flannel pods to be ready
  ansible.builtin.command: kubectl wait --for=condition=Ready pods --all -n kube-system --timeout=300s
  when: flannel_install.changed