---
- name: Create .kube directory for kubeconfig
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0755'

- name: Copy admin.conf to .kube/config
  become: yes
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    flat: yes

- name: Set correct permissions on kubeconfig
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube/config"
    mode: '0600'
