---
- name: Wait until the k8s-worker-join-command secret is available in Key Vault
  azure.azcollection.azure_rm_keyvaultsecret_info:
    vault_uri: "https://{{ kv_name }}.vault.azure.net/"
    name: "k8s-worker-join-command"
    # Add your authentication details here
    subscription_id: "{{ subscription_id }}"
    client_id: "{{ uai_client_id }}"
    auth_source: "msi"
  register: keyvault_info
  retries: 12
  delay: 30
  until: keyvault_info.secrets is defined and keyvault_info.secrets | length > 0 and not keyvault_info.failed
  ignore_errors: true

- name: Retrieve the secret from Key Vault
  azure.azcollection.azure_rm_keyvaultsecret:
    client_id: "{{ uai_client_id }}"
    subscription_id: "{{ subscription_id }}"
    auth_source: "msi"
    keyvault_uri: "https://{{ kv_name }}.vault.azure.net/"
    secret_name: "k8s-worker-join-command"
  register: join_command

  # IMPORTANT: Use 'no_log' in production to prevent the secret from
  # ever being written to logs or the console.
  no_log: true


- name: Join worker node to Kubernetes cluster
  ansible.builtin.command: "{{ join_command.state.secret_value }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  register: join_output
  changed_when: "'This node has joined the cluster' in join_output.stdout"
  failed_when:
    - "'skipped, since /etc/kubernetes/kubelet.conf exists' not in join_output.stdout"
    - "'This node has joined the cluster' not in join_output.stdout"


