---
- name: Initialize the Kubernetes cluster
  ansible.builtin.command: |
    kubeadm init \
      --pod-network-cidr={{ pod_network_cidr }} \
      --control-plane-endpoint="{{ control_plane_endpoint }}:6443" \
      --apiserver-advertise-address="{{ ansible_default_ipv4.address }}" \
      --upload-certs
  args:
    # This is the key for idempotency:
    # The command will NOT run if this file already exists.
    creates: /etc/kubernetes/admin.conf

#- name: Join worker node to Kubernetes cluster
#  ansible.builtin.command: "{{ hostvars['k8s-master']['k8s_join_command'] }}"
#  register: join_output
#  failed_when: "'This node has joined the cluster' not in join_output.stdout and 'already a member of the cluster' not in join_output.stderr"
#  when: "'This node has joined the cluster' not in join_output.stdout and 'already a member of the cluster' not in join_output.stderr"