---
- name: deploy k8s cluster
  hosts: localhost
  become: yes
  vars:
    kubernetes_version: "v1.30" # IMPORTANT: Adjust this to your desired Kubernetes version (e.g., "1.30", "1.31", "1.32")
    # Base URL for Kubernetes package repository.
    # The 'stable' segment is followed by the version.
    kubernetes_repo_base_url: "https://pkgs.k8s.io/core:/stable:/"
  tasks:
    - name: Ensure prerequisites are installed
      ansible.builtin.include_tasks: tasks/common.yaml
    - name: Install containerd
      ansible.builtin.include_tasks: tasks/containerd.yaml
    - name: Install Kubernetes components
      ansible.builtin.import_tasks: tasks/kube_install.yaml
    - name: Initialize Kubernetes Master
      ansible.builtin.import_tasks: tasks/master_init.yaml

- name: Setup Master Access
  hosts: localhosts
  tasks:
    - name: Setup kubeconfig for master access
      ansible.builtin.include_tasks: tasks/setup_master_access.yaml

- name: Install Pod Network Add-on (e.g., Flannel)
  hosts: localhosts
  tasks:
    - name: Install Pod Network Add-on
      ansible.builtin.include_tasks: tasks/pod_network.yaml